# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/dotfiles/.zsh/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle npm
antigen bundle yarn
antigen bundle docker
antigen bundle github
antigen bundle command-not-found

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle jeffreytse/zsh-vi-mode

antigen theme romkatv/powerlevel10k

antigen apply

# User Settings
if command -v kubectl &> /dev/null
then
  source <(kubectl completion zsh)
fi

if command -v npm &> /dev/null
then
  source <(npm completion zsh)
fi

if command -v kustomize &> /dev/null
then
  source <(kustomize completion zsh)
fi
source ~/dotfiles/.zsh/export.zsh
source ~/dotfiles/.zsh/settings.zsh
source ~/dotfiles/.zsh/function.zsh
source ~/dotfiles/.zsh/alias.zsh
source ~/dotfiles/.zsh/github.zsh
source ~/dotfiles/.zsh/forgit.zsh
[[ ! -f /etc/profile.d/autojump.zsh ]] || source /etc/profile.d/autojump.zsh
[[ ! -f ~/dotfiles/tokens/zsh/tokens.zsh ]] || source ~/dotfiles/tokens/zsh/tokens.zsh
[[ ! -f ~/dotfiles/.zsh/.p10k.zsh ]] || source ~/dotfiles/.zsh/.p10k.zsh

# Nodenv init
if command -v nodenv &> /dev/null
then
  eval "$(nodenv init -)"
fi
