# Path to your oh-my-zsh installation.
export ZSH="/Users/$(id -un)/.dotfiles-darwin/oh-my-zsh/"
export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

# User exports
export PATH="/usr/local/sbin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include:/usr/local/sbin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr:/usr/local/bin:/usr/local/Cellar:/usr/bin:/bin:/usr/sbin:/sbin:/usr/include/libxml2:/Users/$(id -un)/Library/Python/2.7/bin:/usr/local/opt/llvm/bin:/usr/local/include:/$(id -un)/dnehrig/Library/Python/3.7/bin:/usr/local/share/dotnet"
export EDITOR='vim'
export DEFAULT_USER="$USER"
export TERM=xterm-256color
export UNCRUSTIFY_CONFIG=~/.dotfiles-darwin/.uncrustify

# User Settings
source ~/.dotfiles-darwin/.zsh/settings.zsh
source ~/.dotfiles-darwin/.zsh/function.zsh
source ~/.dotfiles-darwin/.zsh/alias.zsh
source ~/.dotfiles-darwin/.zsh/tokens.zsh

# Nodenv init
eval "$(nodenv init -)"

# docker machine init
# eval $(docker-machine env)
# export DOCKER_IP=$(docker-machine ip)

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git tmux osx zsh-syntax-highlighting yarn npm docker dnf fzf fzf-docker zsh-autosuggestions)
export FZF_DEFAULT_COMMAND='find . -type f ! -path "*/\.git/*" ! -path "*/\node_modules/*" ! -path "*/\coverage/*" ! -path "*/\npm-packages-offline-cache/*"'
export FZF_CTRL_T_COMMAND='find . -type f ! -path "*/\.git/*" ! -path "*/\node_modules/*" ! -path "*/\coverage/*" ! -path "*/\npm-packages-offline-cache/*"'
export FZF_DEFAULT_OPTS="--preview 'bat --style=numbers --color=always {}'"

source $ZSH/oh-my-zsh.sh
source ~/.dotfiles-darwin/.zsh/forgit.zsh

neofetch

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

